// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyOtckN0-iQMifdlzBNcfC_zVteSMfunU',
    appId: '1:1076712230586:web:651a3e1e47fcd604b07c83',
    messagingSenderId: '1076712230586',
    projectId: 'iiumauditpro-91d98',
    authDomain: 'iiumauditpro-91d98.firebaseapp.com',
    storageBucket: 'iiumauditpro-91d98.appspot.com',
    measurementId: 'G-QL1X8BG7W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKVAESAVmDLAdiuy4kOECHrpimuOYJqIA',
    appId: '1:1076712230586:android:e4c5aafec9235560b07c83',
    messagingSenderId: '1076712230586',
    projectId: 'iiumauditpro-91d98',
    storageBucket: 'iiumauditpro-91d98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv8ohX4nsqJuXlxJQJ4ZJQVMkuuUt-364',
    appId: '1:1076712230586:ios:c28b57bc727364abb07c83',
    messagingSenderId: '1076712230586',
    projectId: 'iiumauditpro-91d98',
    storageBucket: 'iiumauditpro-91d98.appspot.com',
    iosBundleId: 'com.example.audit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv8ohX4nsqJuXlxJQJ4ZJQVMkuuUt-364',
    appId: '1:1076712230586:ios:c28b57bc727364abb07c83',
    messagingSenderId: '1076712230586',
    projectId: 'iiumauditpro-91d98',
    storageBucket: 'iiumauditpro-91d98.appspot.com',
    iosBundleId: 'com.example.audit',
  );
}
